spring.application.name=ai-agent-tester
spring.datasource.url=jdbc:mysql://localhost:3306/agentai_tester
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

openai.api.url=https://api.openai.com/v1/chat/completions

# Define o context path da aplicação
server.servlet.context-path=/ai-agent-tester